export type Lang = "en" | "odia";

export const copy = {
  en: {
    servingOdisha: "Serving Odisha",
    heroTitle: "Construction materials delivered to your site in Odisha",
    slogan: "Build Better.",
    heroSub: "Direct from crushers, transparent pricing, reliable delivery.",
    orderWhatsApp: "Order on WhatsApp",
    callUs: "Call us",
    whatWeSupply: "What we supply",
    whatWeSupplySub: "Quality aggregates and bulk materials for your projects.",
    stoneChipsTitle: "Stone Chips (Aggregates)",
    stoneChipsDesc:
      "Graded stone chips from Chandikhole & Aruha mines. Different sizes for concrete, road base, and filling.",
    stoneDustTitle: "Stone Dust / Quarry Dust",
    stoneDustDesc:
      "Fine stone dust for plastering, block work, and as a stabilising layer. Consistent quality, no adulteration.",
    bulkSupplyTitle: "Bulk Supply for Projects",
    bulkSupplyDesc:
      "Large-volume supply for roads, bridges, and buildings. We coordinate with crushers and transporters for timely delivery.",
    howItWorks: "How it works",
    howItWorksSub: "Simple process—no app, no login. Just reach out.",
    step1Title: "Message or call",
    step1Desc:
      "Tell us your location in Odisha, material type, and approximate quantity via WhatsApp or phone.",
    step2Title: "Confirm price & delivery",
    step2Desc:
      "We share the rate and delivery window. You confirm and we schedule the trip to your site.",
    step3Title: "Delivered to your site",
    step3Desc:
      "Material is delivered at the agreed time. Payment as per our discussion (cash/transfer).",
    whyBhoomigo: "Why BhoomiGo",
    why1: "Zero brokerage—we connect you directly to Chandikhole & Aruha crushers for honest pricing.",
    why2: "Quality verified—we only work with mines known for consistent, high-grade stone materials.",
    why3: "Local expertise—headquartered in Dharmasala, we know every crusher and transporter personally.",
    why4: "Zero hassle—WhatsApp support that understands your local needs and site requirements.",
    trustTitle: "Authenticity you can trust",
    trustSub: "Building in Odisha? We ensure you get exactly what you pay for.",
    livePhotosTitle: "Live Photo Verification",
    livePhotosDesc: "Get photos of your material being loaded at the crusher. No surprises at the site.",
    verifiedWeightTitle: "Verified Weight Slips",
    verifiedWeightDesc: "Every load comes with an official weighbridge slip. You pay for what you receive.",
    localRootsTitle: "Unmatched Personal Care",
    localRootsDesc: "As we grow to serve all of Odisha, we treat every order with the personal care it deserves. Your dream home is our priority.",
    nativeBadge: "Native to Odisha",
    serviceAreas: "Service areas",
    serviceAreasLead: "We currently deliver only within Odisha.",
    serviceAreasDetail:
      "Examples: Cuttack, Bhubaneswar, Jajapur, Keonjhar, Angul, Baleswar, Bhadrak, Chandikhole and nearby areas. If you're in Odisha, message us with your location and we'll confirm if we can serve you.",
    businessHours:
      "Business hours: Mon–Sat, 8 AM – 6 PM (IST). We'll respond to messages as soon as we can.",
    disclaimer:
      "Rates depend on distance, material type and availability. We'll confirm the final price when you place your order.",
    copyright: "© BhoomiGo. Construction materials in Odisha.",
    translateToOdia: "ଓଡ଼ିଆରେ ଦେଖନ୍ତୁ",
    translateToEnglish: "English",
    chatWhatsApp: "Chat on WhatsApp",
    whatsAppTemplate: "Hi BhoomiGo, I need construction materials in Odisha.\n\nDelivery Location: ____\nAddress: ____\nMaterial: ____\nQuantity: ____\nDate: ____",
    supplierNavLink: "For Suppliers",
    supplierFooterLead: "Are you a construction materials supplier?",
    supplierFooterCta: "Supplier Login",
    supplierFooterSignupLink: "New supplier? Register here",
  },
  odia: {
    servingOdisha: "ଓଡ଼ିଶାରେ ସେବା",
    heroTitle: "ଓଡ଼ିଶାରେ ଆପଣଙ୍କ ସାଇଟ୍ ପାଇଁ ନିର୍ମାଣ ସାମଗ୍ରୀ ପହଞ୍ଚାଇ ଦେଉଛୁ",
    slogan: "Build Better.",
    heroSub: "କ୍ରଶରର୍ମାନଙ୍କଠାରୁ ପ୍ରତ୍ୟକ୍ଷ, ସ୍ପଷ୍ଟ ମୂଲ୍ୟ, ବିଶ୍ୱାସଯୋଗ୍ୟ ବିତରଣ ।",
    orderWhatsApp: "ହ୍ୱାଟ୍ସଆପ୍ ରେ ଅର୍ଡର କରନ୍ତୁ",
    callUs: "ଆମକୁ ଫୋନ୍ କରନ୍ତୁ",
    whatWeSupply: "ଆମେ କଣ ଯୋଗାଉଛୁ",
    whatWeSupplySub: "ଆପଣଙ୍କ ପ୍ରୋଜେକ୍ଟ ପାଇଁ ଉଚ୍ଚ ମାନର ଆଗ୍ରିଗେଟ୍ ଓ ବଲ୍କ ସାମଗ୍ରୀ ।",
    stoneChipsTitle: "ପଥର ଚିପ୍ସ୍ (ଆଗ୍ରିଗେଟ୍)",
    stoneChipsDesc:
      "ଚଣ୍ଡିଖୋଲ ଏବଂ ଅରୁହା ଖଣିରୁ ବିଭିନ୍ନ ସାଇଜ୍ ର ପଥର ଚିପ୍ସ୍। କଂକ୍ରିଟ୍ ଓ ରୋଡ୍ କାମ ପାଇଁ ।",
    stoneDustTitle: "ପଥର ଧୂଳି / ଖଣି ଧୂଳି",
    stoneDustDesc:
      "ପ୍ଲାଷ୍ଟରିଂ, ବ୍ଲକ୍ କାମ ଓ ସ୍ଥିରୀକରଣ ପାଇଁ ଫାଇନ୍ ପଥର ଧୂଳି। ସ୍ଥିର ମାନ, ମିଶ୍ରଣ ନାହିଁ।",
    bulkSupplyTitle: "ପ୍ରୋଜେକ୍ଟ୍ ପାଇଁ ବଲ୍କ ସପ୍ଲାଇ",
    bulkSupplyDesc:
      "ରୋଡ୍, ବ୍ରିଜ୍ ଓ ବିଲ୍ଡିଂ ପାଇଁ ବଡ଼ ପରିମାଣ ଯୋଗାଣ। କ୍ରଶର୍ ଓ ଟ୍ରାନ୍ସପୋର୍ଟ୍ ସହିତ ସମନ୍ୱୟ କରି ସମୟାନୁସାରେ ପହଞ୍ଚାଉଛୁ ।",
    howItWorks: "କିପରି କାମ କରେ",
    howItWorksSub: "ସରଳ ପ୍ରକ୍ରିୟା—କୌଣସି ଆପ୍ ନାହିଁ, ଲଗ୍ ଇନ୍ ନାହିଁ। କେବଳ ଯୋଗାଯୋଗ କରନ୍ତୁ ।",
    step1Title: "ମେସେଜ୍ କିମ୍ବା ଫୋନ୍ କରନ୍ତୁ",
    step1Desc:
      "ଓଡ଼ିଶାରେ ଆପଣଙ୍କ ଅବସ୍ଥିତି, ସାମଗ୍ରୀ ପ୍ରକାର ଓ ପରିମାଣ ହ୍ୱାଟ୍ସଆପ୍ କିମ୍ବା ଫୋନ୍ ରେ କହନ୍ତୁ।",
    step2Title: "ମୂଲ୍ୟ ଓ ବିତରଣ ନିଶ୍ଚିତ କରନ୍ତୁ",
    step2Desc:
      "ଆମେ ରେଟ୍ ଓ ଡିଲିଭାରି ସମୟ ଦେଉଛୁ। ଆପଣ ନିଶ୍ଚିତ କଲେ ଆମେ ଆପଣଙ୍କ ସାଇଟ୍ ପାଇଁ ଯାତ୍ରା ପ୍ଲାନ୍ କରୁ।",
    step3Title: "ଆପଣଙ୍କ ସାଇଟ୍ ପାଇଁ ପହଞ୍ଚାଇ ଦେଉଛୁ",
    step3Desc:
      "ସ୍ଥିର ସମୟରେ ସାମଗ୍ରୀ ପହଞ୍ଚିଯାଏ। ଆମ ଆଲୋଚନା ଅନୁଯାୟୀ ପେମେଣ୍ଟ୍ (ନଗଦ/ଟ୍ରାନ୍ସଫର୍) ।",
    whyBhoomigo: "କାହିଁକି ଭୂମିଗୋ",
    why1: "ଜିରୋ ବ୍ରୋକରେଜ୍—ଆମେ ଆପଣଙ୍କୁ ଚଣ୍ଡିଖୋଲ ଓ ଅରୁହା କ୍ରଶର୍ ସହ ସିଧା ଯୋଗୁଁ, ସଠିକ୍ ମୂଲ୍ୟ ପାଆନ୍ତୁ ।",
    why2: "ମାନ ନିଶ୍ଚିତ—ଆମେ କେବଳ ଭଲ ମାନର ପଥର ସାମଗ୍ରୀ ଯୋଗାଉଥିବା ଖଣି ସହ କାମ କରୁ ।",
    why3: "ସ୍ଥାନୀୟ ଅଭିଜ୍ଞତା—ଧର୍ମଶାଳାରେ ଆମର ମୁଖ୍ୟ କାର୍ଯ୍ୟାଳୟ, ଆମେ ସବୁ କ୍ରଶର୍ ଓ ଟ୍ରାନ୍ସପୋର୍ଟର୍ ଙ୍କୁ ଭଲ ଭାବେ ଜାଣୁ ।",
    why4: "ଝଞ୍ଜଟ ମୁକ୍ତ—ହ୍ୱାଟ୍ସଆପ୍ ସହାୟତା ଯାହା ଆପଣଙ୍କ ସ୍ଥାନୀୟ ଆବଶ୍ୟକତାକୁ ବୁଝେ ।",
    trustTitle: "ବିଶ୍ୱାସ ଓ ସ୍ୱଚ୍ଛତା",
    trustSub: "ଓଡ଼ିଶାରେ ଘର ତିଆରି କରୁଛନ୍ତି? ଆମେ ନିଶ୍ଚିତ କରୁଛୁ କି ଆପଣ ଯାହା ପାଇଁ ପେମେଣ୍ଟ୍ କରୁଛନ୍ତି ତାହା ହିଁ ପାଉଛନ୍ତି ।",
    livePhotosTitle: "ଲାଇଭ୍ ଫଟୋ ଭେରିଫିକେସନ୍",
    livePhotosDesc: "ଗାଡ଼ି ଲୋଡିଂ ହେବା ବେଳର ଫଟୋ ପାଆନ୍ତୁ। ସାଇଟ୍ ରେ ପହଞ୍ଚିଲା ବେଳେ କିଛି ସନ୍ଦେହ ରହିବ ନାହିଁ ।",
    verifiedWeightTitle: "ସଠିକ୍ ଓଜନ ସ୍ଲିପ୍",
    verifiedWeightDesc: "ପ୍ରତ୍ୟେକ ଲୋଡ୍ ସହିତ ସରକାରୀ ଧର୍ମକଣ୍ଟା (Weighbridge) ସ୍ଲିପ୍ ମିଳିବ ।",
    localRootsTitle: "ବ୍ୟକ୍ତିଗତ ଦାୟିତ୍ୱବୋଧ",
    localRootsDesc: "ଓଡ଼ିଶାର ସବୁ ସ୍ଥାନରେ ସେବା ଯୋଗାଇବା ପାଇଁ ଆମେ ବଢୁଛୁ, କିନ୍ତୁ ପ୍ରତ୍ୟେକ ଅର୍ଡରକୁ ଆମେ ନିଜର ଭାବି ଯନ୍ତ୍ର ସହ ପହଞ୍ଚାଉଛୁ।",
    nativeBadge: "ଓଡ଼ିଶାର ନିଜସ୍ୱ",
    serviceAreas: "ସେବା କ୍ଷେତ୍ର",
    serviceAreasLead: "ଆମେ ବର୍ତ୍ତମାନ କେବଳ ଓଡ଼ିଶା ଭିତରେ ଯୋଗାଣ କରୁ ।",
    serviceAreasDetail:
      "ଉଦାହରଣ: କଟକ, ଭୁବନେଶ୍ୱର, ଯାଜପୁର, କେଉଁଝର, ଅନୁଗୋଳ, ବାଲେଶ୍ୱର, ଭଦ୍ରକ, ଚଣ୍ଡିଖୋଲ ଓ ନିକଟବର୍ତ୍ତୀ ଅଞ୍ଚଳ। ଯଦି ଆପଣ ଓଡ଼ିଶାରେ ଅଛନ୍ତି, ଆପଣଙ୍କ ଅବସ୍ଥିତି ଲେଖି ପଠାନ୍ତୁ, ଆମେ ସେବା କରିପାରିବା କି ନାହିଁ କହିଦେବୁ ।",
    businessHours:
      "କାମ ଘଣ୍ଟା: ସୋମ–ଶନି, ସକାଳ ୮–ସନ୍ଧ୍ୟା ୬ (IST)। ଯଥାଶୀଘ୍ର ମେସେଜ୍ ର ଉତ୍ତର ଦେବୁ ।",
    disclaimer:
      "ମୂଲ୍ୟ ଦୂରତା, ସାମଗ୍ରୀ ପ୍ରକାର ଓ ଉପଲବ୍ଧତା ଉପରେ ନିର୍ଭର କରେ। ଅର୍ଡର୍ କଲାବେଳେ ଅନ୍ତିମ ମୂଲ୍ୟ ନିଶ୍ଚିତ କରିଦେବୁ ।",
    copyright: "© ଭୂମିଗୋ। ଓଡ଼ିଶାରେ ନିର୍ମାଣ ସାମଗ୍ରୀ ।",
    translateToOdia: "ଓଡ଼ିଆରେ ଦେଖନ୍ତୁ",
    translateToEnglish: "English",
    chatWhatsApp: "ହ୍ୱାଟ୍ସଆପ୍ ରେ ଚାଟ୍ କରନ୍ତୁ",
    whatsAppTemplate: "ନମସ୍ତେ ଭୂମିଗୋ, ମୋତେ ଓଡ଼ିଶାରେ ନିର୍ମାଣ ସାମଗ୍ରୀ ଦରକାର।\n\nଡେଲିଭରି ସ୍ଥାନ: ____\nଠିକଣା: ____\nସାମଗ୍ରୀ: ____\nପରିମାଣ: ____\nତାରିଖ: ____",
    supplierNavLink: "ଯୋଗାଣକାରୀଙ୍କ ପାଇଁ",
    supplierFooterLead: "ଆପଣ ଏକ ନିର୍ମାଣ ସାମଗ୍ରୀ ଯୋଗାଣକାରୀ କି?",
    supplierFooterCta: "ଯୋଗାଣକାରୀ ଲଗଇନ୍",
    supplierFooterSignupLink: "ନୂଆ ଯୋଗାଣକାରୀ? ଏଠାରେ ପଞ୍ଜୀକରଣ କରନ୍ତୁ",
  },
} as const;
